//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientAppointmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int ApId { get; set; }
        public string UserName { get; set; }
        public string PatientName { get; set; }
        public Nullable<int> DeptId { get; set; }
        public Nullable<int> DocId { get; set; }
        public Nullable<int> AvdId { get; set; }
        public string Address { get; set; }
        public string MobileNo { get; set; }
    
        public virtual AvailableDay AvailableDay { get; set; }
        public virtual Department Department { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual User User { get; set; }
    }
}
