//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientAppointmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailableDay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AvailableDay()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int AvdId { get; set; }
        public Nullable<int> DayId { get; set; }
        public Nullable<int> DocId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual Day Day { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
